defaults:
  - scope:
      path: ""
    values:
      layout: default
      style: /asset/layout.css
  
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  
  - scope:
      path: "nullstars"
    values:
      style: /asset/nullstars.css

title: parchii hell
description: a dumping ground for loose thoughts and ideas
author: parchii
url: "https://parchii.neocities.org"

exclude: [
  "*.x.*",
  "license"
]

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-webp

webp:
  enabled: true
  
  quality: 75

  img_dir: ["/asset/image/"]
  exclude: []
  append_ext: false
  nested: true

  formats: [".jpeg", ".jpg", ".png", ".tiff"] 
  gifs: [".gif"]

  regenerate: false

